openapi: "3.0.0"
info:
  version: 1.0.0
  title: Swagger DoorKeeper
  license:
    name: MIT
servers:
  - url: http://localhost:8080/
paths:
  /register:
    post:
      summary: Register booking
      operationId: register
      tags:
        - door
      parameters:
        - in: header
          name: X-Token
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Acceptance result and position
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/RegisterResponse"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /status:
    get:
      summary: Get status of booking
      operationId: getStatus
      tags:
        - door
      parameters:
        - in: header
          name: X-Token
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Position
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/StatusResponse"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /entry:
    post:
      summary: Enter the office
      operationId: entry
      tags:
        - door
      parameters:
        - in: header
          name: X-Token
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Permition
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/EntryResponse"
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /exit:
    post:
      summary: Exit the office
      operationId: exit
      tags:
        - door
      parameters:
        - in: header
          name: X-Token
          schema:
            type: string
          required: true
      responses:
        '200':
          description: Exit
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /capacity:
    patch:
      summary: Set the capacity of the office
      operationId: setCapacity
      tags:
        - door
      parameters:
        - in: header
          name: X-Token
          schema:
            type: string
          required: true
      requestBody:
        description: Optional description in *Markdown*
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CapacityBody'
      responses:
        '200':
          description: Done
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    RegisterResponse:
      type: object
      required:
        - accepted
      properties:
        accepted:
          type: boolean
        position:
          type: integer
          format: int32
    StatusResponse:
      type: object
      required:
        - position
      properties:
        position:
          type: integer
          format: int32
    EntryResponse:
      type: object
      required:
        - permitted
      properties:
        permitted:
          type: boolean
    CapacityBody:
      type: object
      properties:
        capacity:
          type: integer
          format: int32
        percentage:
          type: integer
          format: int32
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
