spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:doorkeeper
    username: doorkeeper
    password: doorkeeper
jwt:
  secret: cRfUjXn2r5u8x/A?D(G+KaPdSgVkYp3s
application:
  initialCapacity: 250
  initialPercentage: 10
  initialMinDistance: 5
  pixelSizeInCm: 10
  image:
    grayScale: true
    threshold: 222
    maxValue: 1000
    thresholdMethod: 0
    matchingThreshold: 4000000
    coloringThreshold: 200
    coloringThresholdMethod: 0
    coloringMaxValue: 255
messaging:
  topic: entry-notification
  serverLocation: ${KAFKA_LOCATION:localhost:9092}
  clientId: doorkeeper
  notifyPosition: 3
